config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :microposts do
	 resource :favorites, only: [:create, :destroy]
	end
  
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  
  resources :retweets, only: [:create, :destroy]
  
  resources :users do
    member do
      get 'followings'
    end
    member do
      get 'followers'
    end
    
    member do
      get 'favorites'
    end
  end 
  

end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  validates :region, presence: true, length: { maximum: 20 }, on: :update
  validates :profile, length: { maximum: 400 }
  
  has_many :microposts
  
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  
  has_many :follower_relationships, class_name:  "Relationship",
                                    foreign_key: "followed_id",
                                    dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  
  
    # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.find_or_create_by(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationship = following_relationships.find_by(followed_id: other_user.id)
    following_relationship.destroy if following_relationship
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end
  
  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
  
  mount_uploader :image, ImageUploader
  
 # favorite
 has_many :favorites
 has_many :favorite_microposts, class_name: "Micropost", through: :favorites, source: :micropost 
 
 
  # retweet 
  # あるユーザーが、リツイートしたつぶやき
  has_many :user_retweet_relations, class_name: "Retweet",
                                     foreign_key: "user_id",
                                     dependent:   :destroy
  has_many :user_retweets, through: :user_retweet_relations, source: :micropost
  
  # あるつぶやきをリツイートしている人
  has_many :retweet_user_relations, class_name: "Retweet",
                                     foreign_key: "micropost_id",
                                     dependent:   :destroy
  has_many :retweeted_users, through: :retweet_user_relations, source: :user
  
    # register retweet 
  def retweet(id)
    user_retweet_relations.create(micropost_id: id)
  end

  # cancel retweet
  def unretweet(id)
    Retweet.find_by(id:id).destroy
  end

  # check if retweeted?
  def retweeted?(micropost)
    user_retweets.include?(micropost)
  end
  
  
  # favorite
  def favorite(micropost)
    favorites.create(micropost_id: micropost.id)
  end
  def unfavorite(micropost)
    favorites.find_by(micropost_id: micropost.id).destroy
  end
  def favorite?(micropost)
    favorite_microposts.include?(micropost)
  end 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 before_action :set_user, only: [:edit, :update, :show]
 before_action :authorization, only: [:edit, :update]

  def show # 追加
    @user = User.find(params[:id])
    @microposts = @user.microposts.order(created_at: :desc)
    @microposts = @microposts.page(params[:page]).per(5).order(created_at: :desc) #paginate
  end

  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
    #  flash[:success] = "Welcome to the Sample App!"
            flash[:success] = t(:user_created) # translate
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def update # 追加
    if @user.update(user_params)
   #   flash[:success] = "profile updated"
            flash[:success] = t(:user_updated) # translate
      redirect_to user_path
    else
      render 'edit'
    end
  end
  
  def edit # 追加
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to root_url, alert: 'Non authorization'
    end
  end
  
  
  def set_user # 追加
     @user = User.find(params[:id])
  end
  
  def authorization # 追加
    if @user != current_user
      flash[:danger] = "Non authorization"
      redirect_to root_path
    end
  end
  
  def followings # 課題
    @user = User.find(params[:id])
    @following_users = @user.following_users
  #  render 'follow'
  end
  
  def followers # 課題
    @user = User.find(params[:id])
    @follower_users = @user.follower_users
    render 'follower'
  end
  
  def index
    @users = User.page(params[:page]).per(5).order(:id)
  end


  def favorites
    @user = User.find(params[:id])
    @microposts = @user.favorite_microposts.page(params[:page])
    respond_to do |format|
      format.html
      format.js
    end
  end
  
  private
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :region, :profile, :image)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_follow_list.html.erb
<% @user.following_users.each do |following_user| %>
  <%= link_to following_user.name, user_path(following_user) %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>Edit</h1>

<div class="row">
    <div class="col-md-6 col-md-offset-3">
        
        <%= form_for(@user) do |f| %>
            <% if @user.errors.present? %>
                <div class="alert alert-danger">
                    <%= alert %>
                    <ul>
                        <% @user.errors.full_messages.each do |full_message| %>
                            <li>
                                <%= full_message %>
                            </li>
                        <% end %>
                    </ul>
                </div>
            <% end %>
            
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
            
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control' %>
            
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control' %>
            
            <%= f.label :password_confirmation, "Confirmation" %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
            
            <%= f.label :region %>
            <%= f.text_field :region, class: 'form-control'  %>
        
            <%= f.label :profile %>
            <%= f.text_area :profile, class: 'form-control'  %>
            
            <%= f.label :image %>
            <%= f.file_field :image %>
            
            <%= f.submit "edit my account", class: "btn btn-large btn-primary" %>
            
        <% end %>
    </div>
</div>

app/views/users/favorites.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= render partial:'shared/user_info', locals: {user: @user} %>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render partial: 'follow_form', locals: { user: @user } if logged_in? %>
    <h3>Favorites (<%= @user.favorites.count %>)</h3>
    <div id="microposts">
    <%= render partial: 'shared/micropost', locals: { microposts: @microposts } %>
    </div>
  </div>
</div>

app/views/users/favorites.js.erb
$("#microposts").html("<%= escape_javascript(render partial: 'shared/micropost', locals: { microposts: @microposts}) %>");

app/views/users/follower.html.erb
<%# 
<% @follower_users.each do |follower_user| %> 
<%#
<%= follower_user.name %>
<%#
<% end %>


<% if @user.follower_users.empty? %>
    <span>No followers</span>
<% else %>
    <h1>Followers list</h1>
    <div class="row">
    <% @user.follower_users.each do |follower_user| %>
      <div class="col-md-4">
      <%= gravatar_for follower_user %>
        <span>ID:<%= follower_user.id %></span>
        <div><%= link_to follower_user.name, user_path(follower_user) %></div>
      </div>
    <% end %>
    </div>
<% end %>

app/views/users/followings.html.erb
<%#
<% @following_users.each do |following_user| %>
<%#
<%= following_user.name %>
<%#
<% end %>


<% if @user.following_users.empty? %>
    <span>No followings</span>
<% else %>
    <h1>Follow list</h1>
    <div class="row">
    <% @user.following_users.each do |following_user| %>
      <div class="col-md-4">
      <%= gravatar_for following_user %>
        <span>ID:<%= following_user.id %></span>
        <div><%= link_to following_user.name, user_path(following_user) %></div>
      </div>
    <% end %>
    </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %> <!-- ここを追加 -->

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
      
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
    <%= @user.region %>
    <br>
    <%= @user.profile %>

　<% if @user.image? %>
　　<%= image_tag @user.image.thumb.url %>
　<% else %>
　　<%= image_tag 'noimage.gif' %>
　<% end %> 
　
    

    <ul class="list-unstyled">  
      <li><%= link_to 'follow', followings_user_path %>（<%= @user.following_users.count %>）</li>
      <li><%= link_to 'follower', followers_user_path %>（<%= @user.follower_users.count %>）</li>
    </ul>

    
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
        <%= paginate(@microposts) %>
      </ol>
    <% end %>
  </div>
  
  


</div>