config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :microposts do
	 resource :favorites, only: [:create, :destroy]
	end
  
  
  resources :sessions, only: [:new, :create, :destroy]
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
  
  resources :retweets, only: [:create, :destroy]
  
  resources :users do
    member do
      get 'followings'
    end
    member do
      get 'followers'
    end
    
    member do
      get 'favorites'
    end
  end 
  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_favorite.html.erb
<%= form_for(current_user.favorites.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :micropost_id, micropost.id %></div>
  <%= f.submit "Favorite", class: "btn btn-primary" %>
<% end %>

app/views/shared/_favorite_form.html.erb
<% if logged_in? %>
  <div id="favorite_form-<%= micropost.id %>">
  <% if current_user.favorite?(micropost) %>
    <%= render partial: 'shared/unfavorite', locals: { micropost: micropost } %>
  <% else %>
    <%= render partial: 'shared/favorite', locals: { micropost: micropost } %>
  <% end %>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
<% end %>

app/views/shared/_micropost.html.erb
<% if microposts.any? %>
  <%= page_entries_info microposts %>
  <ol class="microposts">
    <%= render microposts %>
  </ol>
  <%= paginate microposts, :remote => true %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_unfavorite.html.erb
<%= form_for(current_user.favorites.find_by(micropost_id: micropost.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfavorite", class: "btn" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>
<span><%= link_to pluralize(current_user.favorites.count, "favorite"), favorites_user_path(current_user) %></span>